#[derive(Debug, Clone, PartialEq, Eq)]
pub struct CompanyDetails {
    pub name: String,
    pub formal_name: Option<String>,
    pub guid: Option<String>,
    pub company_number: Option<String>,
    pub starting_from: Option<String>,
    pub books_from: Option<String>,
    pub audited_upto: Option<String>,
    /// Base currency original name/symbol from Tally (`CURRENCYNAME`), e.g. `$` or `?`.
    pub currency_name: Option<String>,
    pub email: Option<String>,
    pub website: Option<String>,
    pub phone_number: Option<String>,
    pub fax_number: Option<String>,
    pub address: Vec<String>,
    pub state_name: Option<String>,
    pub country_name: Option<String>,
    pub country_isd_code: Option<String>,
    pub pincode: Option<String>,
    pub gst_registration_number: Option<String>,
    pub gst_registration_type: Option<String>,
    pub income_tax_number: Option<String>,
    pub is_gst_on: Option<bool>,
    pub is_accounting_on: Option<bool>,
    pub is_inventory_on: Option<bool>,
    pub is_bill_wise_on: Option<bool>,
    pub is_payroll_on: Option<bool>,
    pub is_security_on: Option<bool>,
    pub is_invoicing_on: Option<bool>,
    pub is_multi_currency_on: Option<bool>,
}
